from fastapi import APIRouter, UploadFile, File, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db.dependencies import get_db
from app.models.document import Document
from app.services.document_service import DocumentService
from app.services.ai_service import AIService
from app.core.dependencies import get_current_user

router = APIRouter()


@router.post("/upload")
def upload_document(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):

    filepath = DocumentService.save_file(file)
    content = DocumentService.extract_text(filepath)

    document = Document(
        filename=file.filename,
        filepath=filepath,
        content=content,
        owner_id=current_user.id
    )

    db.add(document)
    db.commit()
    db.refresh(document)

    return {
        "id": document.id,
        "filename": document.filename,
        "characters": len(content)
    }


@router.post("/{document_id}/summary")
def generate_summary(
    document_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.owner_id == current_user.id
        )
        .first()
    )

    if not document:
        raise HTTPException(status_code=404, detail="Document not found")

    try:
        summary = AIService.generate_summary(document.content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return {
        "document_id": document.id,
        "summary": summary
    }


@router.post("/{document_id}/quiz")
def generate_quiz(
    document_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.owner_id == current_user.id
        )
        .first()
    )

    if not document:
        raise HTTPException(status_code=404, detail="Document not found")

    try:
        quiz = AIService.generate_quiz(document.content,document.id,db)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Quiz generation failed: {str(e)}")

    if not quiz or len(quiz) == 0:
        raise HTTPException(
            status_code=500,
            detail="Invalid quiz generated by AI"
        )

    return {
        "document_id": document.id,
        "quiz": quiz
    }